Make bin/deploy run once for both sites.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,42 +1,63 @@
 #/bin/sh
 
-args=("$@")
+function deploy {
+    # Stop RabbitMQ consumers
+    bin/console rabbitmq-supervisor:control stop --wait-for-supervisord
 
-case ${args[0]} in
-PELAGOS)
-    echo 'Setting Encore PublicPath to PELAGOS'
+    # Run composer install to make sure all non-dev dependencies are installed and parameters are defined
+    composer install --no-dev --optimize-autoloader
+
+    # Handle Yarn
+    yarn install
+    yarn run encore prod $publicpath
+
+    # Dump ENV into compiled format
+    composer dump-env prod
+
+    # Warn of any pending migrations, but don't apply them.
+    bin/console doctrine:migrations:status
+
+    # Rebuild Supervisor config for RabbitMQ consumers and start them
+    bin/console rabbitmq-supervisor:rebuild --wait-for-supervisord
+
+    # Rebuild elasticsearch indexes
+    bin/console fos:elastica:reset
+    bin/console fos:elastica:populate
+}
+
+
+if [ $# -eq 0 ]
+  then
+    echo "Please specify branch."
+    exit 1
+fi
+
+branch=$1
+
+# Save current directory before setting.
+export prevDir=$PWD
+
+# PELAGOS
+    cd /opt/pelagos
+    git fetch
+    gitresult=`git checkout $branch`
+    exit 1
+    if [[ "$gitresult" =~ "$error: pathspec".* ]]; then
+        echo "Error. Branch $branch not found."
+        exit 1
+    fi
+    echo 'Setting Encore PublicPath for GRIIDC site.'
     export publicpath="--publicpath /pelagos-symfony/build"
-    ;;
-NAS)
-    echo 'Setting Encore PublicPath to NAS'
+    echo $publicpath
+    #deploy
+# NAS
+    cd /opt/grp
+    git fetch
+    git checkout $branch
+    echo 'Setting Encore PublicPath for GRP Site.'
     export publicpath="--publicpath /build"
-    ;;
-*)
-    echo 'Please specify a Build Environment!'
-    echo 'Options: [PELAGOS, NAS]'
-    exit;
-    ;;
-esac
+    echo $publicpath
+    #deploy
 
-# Stop RabbitMQ consumers
-bin/console rabbitmq-supervisor:control stop --wait-for-supervisord
-
-# Run composer install to make sure all non-dev dependencies are installed and parameters are defined
-composer install --no-dev --optimize-autoloader
-
-# Handle Yarn
-yarn install
-yarn run encore prod $publicpath
-
-# Dump ENV into compiled format
-composer dump-env prod
-
-# Warn of any pending migrations, but don't apply them.
-bin/console doctrine:migrations:status
-
-# Rebuild Supervisor config for RabbitMQ consumers and start them
-bin/console rabbitmq-supervisor:rebuild --wait-for-supervisord
-
-# Rebuild elasticsearch indexes
-bin/console fos:elastica:reset
-bin/console fos:elastica:populate
+# CD back into original starting directory
+cd $prevDir
