Make compatible with podman too.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -10,9 +10,37 @@ RUN microdnf install -y dnf \
     && dnf -qy module disable postgresql \
     && dnf module reset php \
     && dnf module install php:remi-8.3 -y \
-    && dnf install -y tar php php-cli php-common php-mbstring php-pdo php-sodium php-tidy php-xml php-ldap php-intl php-geos php-gd php-pgsql git wget openldap bzip2 unzip zip vim postgresql17 \
+    && dnf install -y tar php php-cli php-common php-mbstring php-pdo php-sodium php-tidy php-xml php-ldap php-intl php-geos php-gd php-pgsql git wget openldap bzip2 unzip zip vim postgresql17\
     && dnf update -y \
     && dnf clean all -y
+
+ENV GOSU_VERSION 1.17
+RUN set -eux; \
+	\
+	rpmArch="$(rpm --query --queryformat='%{ARCH}' rpm)"; \
+	case "$rpmArch" in \
+		aarch64) dpkgArch='arm64' ;; \
+		armv[67]*) dpkgArch='armhf' ;; \
+		i[3456]86) dpkgArch='i386' ;; \
+		ppc64le) dpkgArch='ppc64el' ;; \
+		riscv64 | s390x) dpkgArch="$rpmArch" ;; \
+		x86_64) dpkgArch='amd64' ;; \
+		*) echo >&2 "error: unknown/unsupported architecture '$rpmArch'"; exit 1 ;; \
+	esac; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+# verify the signature
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	gpgconf --kill all; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+# verify that the binary works
+	gosu --version; \
+	gosu nobody true
 
 # Install Symfony, Node.js, npm, Yarn, Composer, and configure php.ini
 RUN wget https://get.symfony.com/cli/installer -O - | bash \
@@ -29,5 +57,7 @@ RUN wget https://get.symfony.com/cli/installer -O - | bash \
     && sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 11M/g' /etc/php.ini \
     && sed -i 's/;date.timezone =/date.timezone = America\/Chicago/g' /etc/php.ini \
     && mkdir -p /san/data/store /san/home/upload/chunks /san/home/upload/files /san/home/http/download \
-    && chmod 777 /san/data/store /san/home/upload/chunks /san/home/upload/files /san/data/store
+    && chmod 777 /san/data/store /san/home/upload/chunks /san/home/upload/files /san/data/store \
+    && groupadd -r devuser \
+    && useradd -r -g devuser -d /opt/pelagos -s /bin/bash devuser
 
